"""Tree of Thoughts (ToT) models and data structures.

This module defines the core data models for the Tree of Thoughts reasoning algorithm,
including candidate solutions and structured output models.
"""

import operator
from typing import Any, Generic, Literal, TypeVar, Union, Optional, List

from pydantic import BaseModel, ConfigDict, Field

# Generic type for solution content
T = TypeVar("T")


class Candidate(BaseModel, Generic[T]):
    """A candidate solution in the Tree of Thoughts algorithm.

    This represents an unscored candidate solution generated by the LLM.
    """

    content: T = Field(description="The candidate solution content")
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata"
    )

    # Use Pydantic v2 configuration
    model_config = ConfigDict(
        validate_assignment=True,
        extra="allow",
        arbitrary_types_allowed=True)

    def __str__(self) -> str:
        """String representation of the candidate."""
        content_str = str(self.content)
        content_preview = (
            content_str[:50] + "..." if len(content_str) > 50 else content_str
        )
        return f"Candidate(content='{content_preview}')"


class Score(BaseModel):
    """A score with feedback.

    This represents the evaluation of a candidate solution.
    """

    value: float = Field(description="Numerical score between 0 and 1", ge=0, le=1)
    feedback: Optional[str] = Field(
        default=None, description="Feedback explaining the score"
    )

    model_config = ConfigDict(
        validate_assignment=True)

    def __str__(self) -> str:
        """String representation of the score."""
        if self.feedback:
            feedback_preview = (
                self.feedback[:30] + "..." if len(self.feedback) > 30 else self.feedback
            )
            return f"Score({self.value}, feedback='{feedback_preview}')"
        return f"Score({self.value})"


class ScoredCandidate(BaseModel, Generic[T]):
    """A candidate solution with its evaluation score.

    This combines a candidate solution with its score and feedback.
    """

    candidate: Candidate[T] = Field(description="The candidate solution")
    score: Score = Field(description="The evaluation score")

    model_config = ConfigDict(
        validate_assignment=True,
        arbitrary_types_allowed=True)

    def __str__(self) -> str:
        """String representation of the scored candidate."""
        return f"ScoredCandidate({self.candidate}, score={self.score})"

    @property
    def content(self) -> T:
        """Get the content of the candidate."""
        return self.candidate.content

    @property
    def value(self) -> float:
        """Get the numerical score value."""
        return self.score.value

    @property
    def feedback(self) -> Optional[str]:
        """Get the feedback if any."""
        return self.score.feedback

    @property
    def metadata(self) -> dict[str, Any]:
        """Get the metadata of the candidate."""
        return self.candidate.metadata


# Helper functions for state management


def update_candidates(
    existing: Optional[List[Any]] = None, updates: Optional[Union[List[Any], str]] = None
) -> list[Any]:
    """Update candidate list, handling special cases like clearing.

    Args:
        existing: Current list of candidates
        updates: New candidates to add, or "clear" to empty the list

    Returns:
        Updated list of candidates
    """
    if existing is None:
        existing = []
    if updates is None:
        return existing
    if updates == "clear":
        return []
    # Concatenate the lists
    return existing + updates


# ======================================================
# Structured Output Models for LLM Responses
# ======================================================


class CandidateGeneration(BaseModel, Generic[T]):
    """Structured output model for generating multiple candidate solutions.

    This model is used when the generator LLM produces structured output.
    """

    reasoning: str = Field(description="The reasoning behind the generated candidates")

    candidate_contents: list[T] = Field(
        description="List of candidate solution contents", min_items=1
    )

    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        json_schema_extra={
            "examples": [
                {
                    "reasoning": "I'll explore different approaches to solve this problem...",
                    "candidate_contents": [
                        "First candidate solution...",
                        "Second candidate solution...",
                        "Third candidate solution...",
                    ],
                }
            ]
        })

    def to_candidates(self) -> list[Candidate[T]]:
        """Convert candidate contents to Candidate objects."""
        return [Candidate(content=content) for content in self.candidate_contents]


class CandidateEvaluation(BaseModel):
    """Structured output model for evaluating a candidate solution.

    This model is used when the evaluator LLM produces structured output.
    """

    value: float = Field(
        description="Score between 0 and 1, where 1 is perfect", ge=0, le=1
    )

    feedback: str = Field(description="Feedback explaining the score")

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "value": 0.85,
                    "feedback": "This solution is good because... However, it could be improved by...",
                }
            ]
        }
    )

    def to_score(self) -> Score:
        """Convert to a Score object."""
        return Score(value=self.value, feedback=self.feedback)


# ======================================================
# Example of a specific solution type - Equation (for Game of 24 etc.)
# ======================================================

# Type definitions for equation tokens
OperatorType = Literal["+", "-", "*", "/"]
TokenType = Union[float, OperatorType]


class Equation(BaseModel):
    """An equation in reverse-polish notation that combines numbers to reach a target value.

    This is one possible implementation of a solution type for mathematical problems.
    """

    tokens: list[TokenType] = Field(
        description="The stack of tokens and operators in reverse-polish notation. Example: [3, 4, '+', -1, '*'] would evaluate to (3 + 4) * -1 = -7."
    )

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {"tokens": [3.0, 4.0, "+", -1.0, "*"]},
                {"tokens": [7.0, 5.0, "*", 12.0, "/"]},
            ]
        }
    )

    def compute(self) -> float:
        """Compute the result of the equation."""
        op_funcs = {
            "+": operator.add,
            "-": operator.sub,
            "*": operator.mul,
            "/": operator.truediv,
        }
        stack = []
        for token in self.tokens:
            if isinstance(token, float):
                stack.append(token)
            else:
                b, a = stack.pop(), stack.pop()
                stack.append(op_funcs[token](a, b))

        return stack[0]

    def __str__(self) -> str:
        """String representation of the equation."""
        try:
            result = self.compute()
            return f"Equation({self.tokens}) = {result}"
        except Exception as e:
            return f"Equation({self.tokens}) [Error: {e}]"


class EquationGeneration(BaseModel):
    """Specialized candidate generation for equation problems.

    This is a structured output model for equation-specific generation.
    """

    reasoning: str = Field(description="The reasoning behind the generated equations")

    equations: list[Equation] = Field(
        description="List of equation solutions", min_items=1
    )

    explanations: Optional[List[str]] = Field(
        default=None, description="Optional explanations for each equation"
    )

    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        json_schema_extra={
            "examples": [
                {
                    "reasoning": "I'll try different combinations of operations...",
                    "equations": [
                        {"tokens": [3.0, 4.0, "+", 8.0, "*"]},
                        {"tokens": [4.0, 8.0, "+", 3.0, "*"]},
                    ],
                    "explanations": [
                        "Using the numbers in RPN: 3 4 + 8 *",
                        "Grouping differently: 3 * (4 + 8)",
                    ],
                }
            ]
        })

    def to_candidates(self) -> list[Candidate[Equation]]:
        """Convert equations to Candidate objects."""
        candidates = []

        # If we have explanations, use them as metadata
        if self.explanations and len(self.explanations) == len(self.equations):
            for i, equation in enumerate(self.equations):
                candidates.append(
                    Candidate(
                        content=equation, metadata={"explanation": self.explanations[i]}
                    )
                )
        else:
            # Otherwise just use the equations
            candidates = [Candidate(content=eq) for eq in self.equations]

        return candidates
