#!/usr/bin/env python3
"""Organize problematic test files and examples.

This script helps organize test files that have syntax errors or are
outdated, moving them to appropriate archive directories.
"""

import shutil
from pathlib import Path
from typing import List, Tuple

# Files with known syntax errors that should be archived
PROBLEM_FILES = [
    # Test files with syntax errors
    "tests/ltm/test_real_langmem.py",
    "tests/integration/supabase/test_supabase_working.py",
    "tests/integration/supabase/test_supabase_complete.py",
    "tests/uncategorized/test_notebook_untitled83.py",
    # Example files that may be outdated
    "examples/simple_agent_v3_example.py",  # Has some issues
    # Other problematic files found during analysis
    "debug_multi_agent_routing.py",
]

# Archive directories to create
ARCHIVE_DIRS = [
    "archive/tests/syntax_errors",
    "archive/tests/integration",
    "archive/tests/uncategorized",
    "archive/examples/v3",
    "archive/debug_scripts",
]


def create_archive_structure() -> None:
    """Create archive directory structure."""
    print("📁 Creating archive directory structure...")

    for archive_dir in ARCHIVE_DIRS:
        Path(archive_dir).mkdir(parents=True, exist_ok=True)
        print(f"   ✅ Created: {archive_dir}")


def move_problem_files() -> List[Tuple[str, str]]:
    """Move problematic files to archive."""
    moved_files = []

    print("\n📦 Moving problematic files to archive...")

    for file_path in PROBLEM_FILES:
        source = Path(file_path)

        if not source.exists():
            print(f"   ⚠️  File not found: {file_path}")
            continue

        # Determine destination based on file type and location
        if "tests/ltm/" in file_path:
            dest_dir = "archive/tests/syntax_errors"
        elif "tests/integration/" in file_path:
            dest_dir = "archive/tests/integration"
        elif "tests/uncategorized/" in file_path:
            dest_dir = "archive/tests/uncategorized"
        elif "examples/" in file_path and "v3" in file_path:
            dest_dir = "archive/examples/v3"
        elif file_path.startswith("debug_"):
            dest_dir = "archive/debug_scripts"
        else:
            dest_dir = "archive/tests/syntax_errors"

        destination = Path(dest_dir) / source.name

        try:
            shutil.move(str(source), str(destination))
            moved_files.append((file_path, str(destination)))
            print(f"   ✅ Moved: {file_path} → {destination}")
        except Exception as e:
            print(f"   ❌ Failed to move {file_path}: {e}")

    return moved_files


def create_archive_readme() -> None:
    """Create README for archive directory."""
    readme_content = """# Archive Directory

This directory contains files that were moved from the main codebase due to:

## Syntax Errors
- Test files with syntax errors that prevent formatting/linting
- Files with encoding issues or malformed code

## Integration Tests  
- Integration tests that may be outdated or non-functional
- Tests that depend on external services that aren't available

## Outdated Examples
- Example files from older versions (v3, etc.)
- Examples that may not work with current API

## Debug Scripts
- One-off debug scripts that aren't part of main codebase
- Temporary debugging utilities

## Restoration
To restore a file from archive:
1. Fix any syntax errors
2. Update to current API if needed
3. Add proper tests
4. Move back to appropriate location

Generated by: organize_problem_files.py
"""

    with open("archive/README.md", "w") as f:
        f.write(readme_content)

    print("\n📝 Created archive/README.md")


def scan_for_additional_problems() -> List[str]:
    """Scan for additional files that might need archiving."""
    print("\n🔍 Scanning for additional problematic files...")

    problem_patterns = [
        "test_notebook_untitled*.py",
        "*_temp.py",
        "*_debug.py",
        "*_old.py",
        "*_backup.py",
    ]

    additional_problems = []

    for pattern in problem_patterns:
        matches = list(Path(".").rglob(pattern))
        for match in matches:
            if match.is_file() and str(match) not in PROBLEM_FILES:
                additional_problems.append(str(match))
                print(f"   ⚠️  Found: {match}")

    return additional_problems


def main():
    """Main organization function."""
    print("🗂️  Haive-Agents File Organization Script")
    print("=" * 50)

    # Create archive structure
    create_archive_structure()

    # Move known problem files
    moved_files = move_problem_files()

    # Create archive README
    create_archive_readme()

    # Scan for additional problems
    additional_problems = scan_for_additional_problems()

    # Summary
    print("\n📊 Organization Summary:")
    print(f"   📦 Files moved to archive: {len(moved_files)}")
    print(f"   ⚠️  Additional problems found: {len(additional_problems)}")

    if moved_files:
        print("\n✅ Successfully moved files:")
        for source, dest in moved_files:
            print(f"   {source} → {dest}")

    if additional_problems:
        print("\n⚠️  Additional files that might need attention:")
        for file_path in additional_problems[:10]:  # Show first 10
            print(f"   {file_path}")
        if len(additional_problems) > 10:
            print(f"   ... and {len(additional_problems) - 10} more")

    print("\n🎉 Organization complete!")
    print("   Run 'trunk check --all' to verify remaining files are clean")


if __name__ == "__main__":
    main()
