"""Module exports."""

from haive.agents.discovery.component_discovery_agent import (  # clear_cache,  # Instance method, not module function; get_cache_stats,  # Instance method, not module function; setup_discovery_agent,  # Instance method, not module function
    ComponentDiscoveryAgent,
)
from haive.agents.discovery.dynamic_tool_selector import (
    ContextAwareSelector,
    ContextAwareState,
    DynamicToolSelector,
    LangGraphStyleSelector,
    SelectionMode,
    ToolBindingStrategy,
    ToolSelectionResult,
    ToolSelectionStrategy,
    ToolUsageStats,
    create_context_aware_selector,
    create_dynamic_tool_selector,
    create_langgraph_style_selector,
    create_tool_selection_node,
    placeholder_function,
    setup_selector,
)
from haive.agents.discovery.selection_strategies import (
    AdaptiveSelectionStrategy,
    BaseSelectionStrategy,
    CapabilityBasedStrategy,
    ContextualSelectionStrategy,
    EnsembleSelectionStrategy,
    LearningSelectionStrategy,
    SemanticSelectionStrategy,
    add_feedback,
    create_selection_strategy,
    update_performance,
)
from haive.agents.discovery.semantic_discovery import (
    CapabilityMatcher,
    DiscoveryMode,
    EmbeddingProvider,
    QueryAnalysis,
    QueryAnalyzer,
    SemanticDiscoveryEngine,
    ToolSelectionStrategy,
    VectorBasedToolSelector,
    analyze_query,
    build_capability_matrix,
    embed_documents,
    embed_query,
    index_tools,
    match_tools,
    setup_registry,
    setup_vector_store,
    update_selection_strategy,
)

__all__ = [
    "AdaptiveSelectionStrategy",
    "BaseSelectionStrategy",
    "CapabilityBasedStrategy",
    "CapabilityMatcher",
    "ComponentDiscoveryAgent",
    "ContextAwareSelector",
    "ContextAwareState",
    "ContextualSelectionStrategy",
    "DiscoveryMode",
    "DynamicToolSelector",
    "EmbeddingProvider",
    "EnsembleSelectionStrategy",
    "LangGraphStyleSelector",
    "LearningSelectionStrategy",
    "QueryAnalysis",
    "QueryAnalyzer",
    "SelectionMode",
    "SemanticDiscoveryEngine",
    "SemanticSelectionStrategy",
    "ToolBindingStrategy",
    "ToolSelectionResult",
    "ToolSelectionStrategy",
    "ToolUsageStats",
    "VectorBasedToolSelector",
    "add_feedback",
    "analyze_query",
    "build_capability_matrix",
    # "clear_cache",  # Instance method
    "create_context_aware_selector",
    "create_dynamic_tool_selector",
    "create_langgraph_style_selector",
    "create_selection_strategy",
    "create_tool_selection_node",
    "embed_documents",
    "embed_query",
    # "get_cache_stats",  # Instance method
    "index_tools",
    "match_tools",
    "placeholder_function",
    # "setup_discovery_agent",  # Instance method
    "setup_registry",
    "setup_selector",
    "setup_vector_store",
    "update_performance",
    "update_selection_strategy",
]
