#!/usr/bin/env python3
"""Advanced Meta-Agent Patterns with MetaStateSchema.

This module demonstrates sophisticated patterns for creating meta-capable agents
using MetaStateSchema for agent embedding, dynamic replacement, recompilation
tracking, and advanced composition patterns.

Examples:
    Basic meta-capable agent::

        agent = SimpleAgent(name="worker", engine=config)
        meta_state = MetaStateSchema.from_agent(agent)
        result = await meta_state.execute_agent({"query": "Hello"})

    Dynamic agent replacement::

        # Start with v1, dynamically upgrade to v2
        await meta_state.execute_agent(input1)
        meta_state.update_agent(agent_v2)
        await meta_state.execute_agent(input2)

    Multi-agent coordination::

        # Coordinate specialized agents with meta capabilities
        planner_meta = MetaStateSchema.from_agent(planner)
        executor_meta = MetaStateSchema.from_agent(executor)
        result = await coordinate_agents([planner_meta, executor_meta], task)

    Hierarchical agent systems::

        # Build agent hierarchies with meta-state management
        team = HierarchicalAgentSystem()
        await team.execute_complex_workflow(project_spec)
"""

import asyncio
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional, Union

from haive.core.engine.aug_llm import AugLLMConfig
from haive.core.schema.prebuilt.messages_state import MessagesState
from haive.core.schema.prebuilt.meta_state import MetaStateSchema
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.tools import tool
from pydantic import BaseModel, Field

from haive.agents.react.agent import ReactAgent
from haive.agents.simple.agent_v3 import SimpleAgentV3

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# Structured output models for advanced patterns
class TaskPlan(BaseModel):
    """Plan generated by planning agent."""

    objectives: List[str] = Field(description="Main objectives to accomplish")
    steps: List[str] = Field(description="Ordered steps to execute")
    estimated_time: int = Field(description="Estimated time in minutes")
    resources_needed: List[str] = Field(description="Required resources")


class ExecutionResult(BaseModel):
    """Result from task execution."""

    completed_steps: List[str] = Field(description="Steps that were completed")
    outcomes: Dict[str, str] = Field(description="Outcomes for each step")
    success_rate: float = Field(ge=0.0, le=1.0, description="Success rate (0-1)")
    recommendations: List[str] = Field(description="Recommendations for improvement")


class AgentPerformanceMetrics(BaseModel):
    """Performance metrics for meta-agent tracking."""

    execution_count: int = Field(default=0)
    average_response_time: float = Field(default=0.0)
    success_rate: float = Field(default=1.0, ge=0.0, le=1.0)
    last_recompilation: Optional[datetime] = None
    recompilation_count: int = Field(default=0)


# Example 1: Basic Meta-Capable Agent Pattern
async def basic_meta_agent_example():
    """Demonstrate basic meta-capable agent with execution tracking."""
    logger.info("=== Basic Meta-Capable Agent Example ===")

    # Create a simple agent
    agent = SimpleAgentV3(
        name="analyzer",
        engine=AugLLMConfig(
            temperature=0.7,
            system_message="You are a data analyzer that provides clear insights.",
        ),
        prompt_template=ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "You are a data analyzer. Analyze the given data and provide insights.",
                ),
                ("human", "Analyze this data: {data}"),
            ]
        ),
    )

    # Make it meta-capable
    meta_state = MetaStateSchema.from_agent(
        agent=agent,
        initial_state={"analysis_mode": "standard"},
        graph_context={"purpose": "data_analysis", "version": "1.0"},
    )

    logger.info(f"Created meta-capable agent: {meta_state.agent_name}")

    # Execute with tracking
    test_data = {
        "data": "Sales: Q1=100k, Q2=150k, Q3=180k, Q4=220k. Costs: Q1=80k, Q2=90k, Q3=95k, Q4=100k"
    }

    result = await meta_state.execute_agent(input_data=test_data, update_state=True)

    # Check execution summary
    summary = meta_state.get_execution_summary()
    logger.info(f"Execution summary: {summary}")

    # Verify meta-capability features
    assert meta_state.execution_count == 1
    assert meta_state.execution_status in ["completed", "success"]
    assert not meta_state.needs_recompile

    logger.info("✅ Basic meta-capable agent working correctly")
    return meta_state, result


# Example 2: Dynamic Agent Replacement Pattern
async def dynamic_agent_replacement_example():
    """Demonstrate dynamic agent replacement with recompilation tracking."""
    logger.info("=== Dynamic Agent Replacement Example ===")

    # Start with a basic analysis agent
    agent_v1 = SimpleAgentV3(
        name="analyzer_v1",
        engine=AugLLMConfig(
            temperature=0.3, system_message="You are a basic data analyzer."
        ),
    )

    # Create meta state
    meta_state = MetaStateSchema.from_agent(
        agent=agent_v1,
        graph_context={"version": "1.0", "capabilities": ["basic_analysis"]},
    )

    # Execute with v1
    logger.info("Executing with agent v1...")
    result_v1 = await meta_state.execute_agent(
        {"data": "Revenue trends over 4 quarters"}
    )

    logger.info(f"V1 execution count: {meta_state.execution_count}")

    # Create enhanced agent v2 with structured output
    agent_v2 = SimpleAgentV3(
        name="analyzer_v2",
        engine=AugLLMConfig(
            temperature=0.3,
            structured_output_model=TaskPlan,
            system_message="You are an advanced strategic analyzer that creates detailed plans.",
        ),
        prompt_template=ChatPromptTemplate.from_messages(
            [
                ("system", "Create a detailed analysis plan for the given data."),
                ("human", "Create a strategic analysis plan for: {data}"),
            ]
        ),
    )

    # Dynamic replacement - this triggers recompilation
    logger.info("Replacing with enhanced agent v2...")
    meta_state.update_agent(agent_v2)

    # Verify recompilation was triggered
    assert meta_state.needs_recompile
    logger.info(f"Recompilation needed: {meta_state.last_recompile_reason}")

    # Execute with v2 - this should handle recompilation
    result_v2 = await meta_state.execute_agent(
        {"data": "Market expansion strategy for Q1-Q4"}
    )

    # Verify upgrade
    assert meta_state.agent_name == "analyzer_v2"
    assert meta_state.execution_count == 2  # Both v1 and v2 executions

    logger.info("✅ Dynamic agent replacement working correctly")
    return meta_state, result_v1, result_v2


# Example 3: Multi-Agent Coordination Pattern
async def multi_agent_coordination_example():
    """Demonstrate coordination of multiple meta-capable agents."""
    logger.info("=== Multi-Agent Coordination Example ===")

    # Create planning agent
    @tool
    def research_tool(query: str) -> str:
        """Research information about a topic."""
        return f"Research results for '{query}': Found relevant data and trends."

    planner = ReactAgent(
        name="strategic_planner",
        engine=AugLLMConfig(
            temperature=0.3,
            system_message="You are a strategic planner. Create comprehensive plans.",
        ),
        tools=[research_tool],
    )

    # Create execution agent
    executor = SimpleAgentV3(
        name="task_executor",
        engine=AugLLMConfig(
            temperature=0.5,
            structured_output_model=ExecutionResult,
            system_message="You are a task executor. Execute plans and report results.",
        ),
    )

    # Make both meta-capable with shared context
    shared_context = {
        "workflow_id": "strategic_execution",
        "coordination_mode": "sequential",
        "shared_memory": {},
    }

    planner_meta = MetaStateSchema.from_agent(
        agent=planner, initial_state={"role": "planner"}, graph_context=shared_context
    )

    executor_meta = MetaStateSchema.from_agent(
        agent=executor, initial_state={"role": "executor"}, graph_context=shared_context
    )

    # Sequential coordination
    task = "Develop a customer retention strategy for Q2"

    logger.info("Step 1: Planning phase...")
    planning_result = await planner_meta.execute_agent(
        {
            "messages": [
                {"role": "user", "content": f"Create a strategic plan for: {task}"}
            ]
        }
    )

    # Store planning result in shared context
    shared_context["shared_memory"]["plan"] = planning_result

    logger.info("Step 2: Execution phase...")
    execution_result = await executor_meta.execute_agent(
        {"plan": planning_result["output"], "task": task}
    )

    # Verify coordination
    assert planner_meta.execution_count == 1
    assert executor_meta.execution_count == 1
    assert "plan" in shared_context["shared_memory"]

    logger.info("✅ Multi-agent coordination working correctly")
    return planner_meta, executor_meta, planning_result, execution_result


# Example 4: Hierarchical Agent System Pattern
class HierarchicalAgentSystem:
    """Advanced hierarchical agent system with meta-state management."""

    def __init__(self):
        """Initialize the hierarchical agent system."""
        self.agents: Dict[str, MetaStateSchema] = {}
        self.hierarchy: Dict[str, List[str]] = {}
        self.performance_metrics: Dict[str, AgentPerformanceMetrics] = {}
        self.global_context = {"system_status": "ready"}

    def add_agent(
        self, role: str, agent: Any, parent: Optional[str] = None
    ) -> MetaStateSchema:
        """Add an agent to the hierarchy."""
        meta_state = MetaStateSchema.from_agent(
            agent=agent,
            initial_state={"role": role, "parent": parent},
            graph_context=self.global_context,
        )

        self.agents[role] = meta_state
        self.performance_metrics[role] = AgentPerformanceMetrics()

        # Update hierarchy
        if parent:
            if parent not in self.hierarchy:
                self.hierarchy[parent] = []
            self.hierarchy[parent].append(role)

        logger.info(f"Added agent '{role}' to hierarchy under '{parent}'")
        return meta_state

    async def execute_workflow(self, workflow_spec: Dict[str, Any]) -> Dict[str, Any]:
        """Execute a complex workflow using the agent hierarchy."""
        logger.info("Executing hierarchical workflow...")

        results = {}
        start_time = datetime.now()

        # Execute in hierarchy order
        execution_order = self._get_execution_order()

        for role in execution_order:
            agent_meta = self.agents[role]
            metrics = self.performance_metrics[role]

            agent_start = datetime.now()

            try:
                # Prepare input based on workflow spec and previous results
                agent_input = self._prepare_agent_input(role, workflow_spec, results)

                result = await agent_meta.execute_agent(agent_input, update_state=True)
                results[role] = result

                # Update metrics
                execution_time = (datetime.now() - agent_start).total_seconds()
                metrics.execution_count += 1
                metrics.average_response_time = (
                    metrics.average_response_time * (metrics.execution_count - 1)
                    + execution_time
                ) / metrics.execution_count

                # Check if agent needs recompilation
                if agent_meta.check_agent_recompilation():
                    metrics.recompilation_count += 1
                    metrics.last_recompilation = datetime.now()
                    logger.info(f"Agent '{role}' scheduled for recompilation")

                logger.info(f"Agent '{role}' completed in {execution_time:.2f}s")

            except Exception as e:
                logger.error(f"Agent '{role}' failed: {e}")
                metrics.success_rate *= 0.9  # Penalize failure
                results[role] = {"error": str(e)}

        total_time = (datetime.now() - start_time).total_seconds()
        logger.info(f"Workflow completed in {total_time:.2f}s")

        return {
            "results": results,
            "execution_time": total_time,
            "performance_metrics": {
                role: {
                    "execution_count": metrics.execution_count,
                    "avg_response_time": metrics.average_response_time,
                    "success_rate": metrics.success_rate,
                    "recompilation_count": metrics.recompilation_count,
                }
                for role, metrics in self.performance_metrics.items()
            },
        }

    def _get_execution_order(self) -> List[str]:
        """Determine execution order based on hierarchy."""
        # Simple topological sort for demonstration
        order = []
        visited = set()

        def visit(role: str):
            if role in visited:
                return
            visited.add(role)

            # Visit children first (bottom-up execution)
            for child in self.hierarchy.get(role, []):
                visit(child)

            order.append(role)

        # Start with root nodes (no parent)
        roots = [
            role
            for role, meta in self.agents.items()
            if meta.agent_state.get("parent") is None
        ]

        for root in roots:
            visit(root)

        return order

    def _prepare_agent_input(
        self, role: str, workflow_spec: Dict[str, Any], results: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Prepare input for an agent based on workflow spec and previous results."""
        base_input = workflow_spec.get(role, {})

        # Add results from dependencies
        agent_meta = self.agents[role]
        parent = agent_meta.agent_state.get("parent")

        if parent and parent in results:
            base_input["parent_result"] = results[parent]

        # Add relevant results from peers
        base_input["context"] = {
            key: value
            for key, value in results.items()
            if key != role  # Don't include self
        }

        return base_input


async def hierarchical_agent_system_example():
    """Demonstrate hierarchical agent system with advanced patterns."""
    logger.info("=== Hierarchical Agent System Example ===")

    # Create the system
    system = HierarchicalAgentSystem()

    # Add director (top level)
    director = SimpleAgentV3(
        name="project_director",
        engine=AugLLMConfig(
            temperature=0.3,
            system_message="You are a project director. Provide high-level guidance and decisions.",
        ),
    )
    system.add_agent("director", director)

    # Add team leads (middle level)
    dev_lead = SimpleAgentV3(
        name="dev_team_lead",
        engine=AugLLMConfig(
            temperature=0.4,
            system_message="You are a development team lead. Plan and coordinate development tasks.",
        ),
    )
    system.add_agent("dev_lead", dev_lead, parent="director")

    # Add individual contributors (bottom level)
    developer = SimpleAgentV3(
        name="senior_developer",
        engine=AugLLMConfig(
            temperature=0.5,
            structured_output_model=ExecutionResult,
            system_message="You are a senior developer. Implement features and solve technical problems.",
        ),
    )
    system.add_agent("developer", developer, parent="dev_lead")

    tester = SimpleAgentV3(
        name="qa_tester",
        engine=AugLLMConfig(
            temperature=0.3,
            system_message="You are a QA tester. Test features and report issues.",
        ),
    )
    system.add_agent("tester", tester, parent="dev_lead")

    # Define workflow
    workflow_spec = {
        "director": {
            "task": "Review project requirements for new authentication system",
            "deliverable": "Strategic direction and resource allocation",
        },
        "dev_lead": {
            "task": "Create development plan based on director guidance",
            "deliverable": "Technical roadmap and task assignments",
        },
        "developer": {
            "task": "Implement authentication features based on team lead plan",
            "deliverable": "Code implementation and documentation",
        },
        "tester": {
            "task": "Test authentication system based on development completion",
            "deliverable": "Test results and quality assessment",
        },
    }

    # Execute workflow
    workflow_result = await system.execute_workflow(workflow_spec)

    # Verify results
    assert "results" in workflow_result
    assert "performance_metrics" in workflow_result
    assert len(workflow_result["results"]) == 4  # All agents executed

    # Check that hierarchy was respected
    results = workflow_result["results"]
    assert all(
        role in results for role in ["director", "dev_lead", "developer", "tester"]
    )

    logger.info("✅ Hierarchical agent system working correctly")
    return system, workflow_result


# Example 5: Advanced Recompilation Tracking
async def recompilation_tracking_example():
    """Demonstrate advanced recompilation tracking and management."""
    logger.info("=== Advanced Recompilation Tracking Example ===")

    # Create agent with dynamic capabilities
    agent = SimpleAgentV3(name="adaptive_agent", engine=AugLLMConfig(temperature=0.7))

    meta_state = MetaStateSchema.from_agent(
        agent=agent, graph_context={"features": ["basic"], "version": "1.0"}
    )

    # Initial execution
    await meta_state.execute_agent({"query": "Basic task"})

    # Simulate configuration change requiring recompilation
    meta_state.graph_context["features"].append("advanced_analytics")
    meta_state.mark_for_recompile("Added advanced analytics feature")

    assert meta_state.needs_recompile
    logger.info(f"Recompilation needed: {meta_state.last_recompile_reason}")

    # Simulate successful recompilation
    meta_state.resolve_recompile(success=True)
    assert not meta_state.needs_recompile

    # Add another feature and track multiple recompilations
    meta_state.graph_context["features"].append("ml_integration")
    meta_state.mark_for_recompile("Added ML integration")

    # Execute after recompilation need
    result = await meta_state.execute_agent({"query": "Advanced task with ML"})

    # Check recompilation history
    summary = meta_state.get_execution_summary()
    logger.info(f"Recompilation tracking: {summary}")

    logger.info("✅ Recompilation tracking working correctly")
    return meta_state, result


# Main execution function
async def run_all_examples():
    """Run all meta-agent pattern examples."""
    logger.info("🚀 Running Advanced Meta-Agent Pattern Examples")

    try:
        # Example 1: Basic meta-capable agent
        meta_state1, result1 = await basic_meta_agent_example()

        # Example 2: Dynamic agent replacement
        meta_state2, result_v1, result_v2 = await dynamic_agent_replacement_example()

        # Example 3: Multi-agent coordination
        planner_meta, executor_meta, plan_result, exec_result = (
            await multi_agent_coordination_example()
        )

        # Example 4: Hierarchical agent system
        system, workflow_result = await hierarchical_agent_system_example()

        # Example 5: Advanced recompilation tracking
        meta_state5, result5 = await recompilation_tracking_example()

        logger.info("🎉 All examples completed successfully!")

        return {
            "basic_meta": (meta_state1, result1),
            "dynamic_replacement": (meta_state2, result_v1, result_v2),
            "coordination": (planner_meta, executor_meta, plan_result, exec_result),
            "hierarchical": (system, workflow_result),
            "recompilation": (meta_state5, result5),
        }

    except Exception as e:
        logger.error(f"❌ Error running examples: {e}")
        raise


if __name__ == "__main__":
    # Run the examples
    results = asyncio.run(run_all_examples())

    print("\n" + "=" * 50)
    print("ADVANCED META-AGENT PATTERNS SUMMARY")
    print("=" * 50)
    print("✅ Basic Meta-Capable Agent - Agent embedding with execution tracking")
    print("✅ Dynamic Agent Replacement - Runtime agent swapping with recompilation")
    print("✅ Multi-Agent Coordination - Sequential coordination with shared context")
    print(
        "✅ Hierarchical Agent System - Complex agent hierarchies with performance tracking"
    )
    print("✅ Recompilation Tracking - Advanced recompilation management")
    print(
        "\nAll patterns demonstrated the power of MetaStateSchema for advanced agent composition!"
    )
